### PR TITLE
support for resetting wave channel externally (say, after some sample playback)

### PR DESCRIPTION
**Pull request by untoxa**

### CODE REVIEW

**Comment by SuperDisk** [comment]
Hmm, is there any reason this needs to be a callable procedure? Why not just expose the memory location and let the user write to it directly?

**Comment by untoxa** [comment]
That’s better for C. I also exposed bare variable for handling it in ISR.

**Comment by untoxa** [comment]
Probably you are right, i’ll make an inline function, that should be better, keeping the same api. I’ll push a new commit with it later.

**Comment by untoxa** [comment]
here

**Comment by SuperDisk** [comment]
Should the banked version have __banked?

**Comment by untoxa** [comment]
no. it is inline function.

**Comment by SuperDisk** [comment]
Why have 2 identical versions then?

**Comment by untoxa** [comment]
that is ok.

**Comment by untoxa** [comment]
homogeneous naming of api functions

**Pull request merged**
